services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}
